### ISSUE TITLE
Synaptics, Inc. 06cb:00a2 fingerprint reader in Lenovo Thinkpad E490

### ISSUE THREAD

**Issue by sebinbenjamin** [nekdolan/ubuntu-certified-non-working#1]
06cb:00a2 fingerprint reader does not work in Lenovo E490.

![image](https://user-images.githubusercontent.com/4099066/66489536-68dcb200-eacd-11e9-9a6d-e7d125e79cc7.png)

**Comment by nekdolan** [comment]
The E490 is not certified by Ubuntu https://certification.ubuntu.com/catalog/component/06cb:00a2 only the L390 .
